## Add Sentiment Analysis as Column

This jupyter book involves of calling the review dataset and read reviews to add a new column with sentiment analysis result of the review.

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy.stats import iqr
import matplotlib.pyplot as plt
from datetime import datetime, date
import transformers
from transformers import pipeline
import torch

path=r"C:\Users\Metin\Desktop\Data Science - Jupyter\britishairlines_internship\data\BA_reviews_depth.csv"

df=pd.read_csv(path)



df['Review'] = df['Review'].map(lambda x: x.lstrip('âœ… Trip Verified | '))
df['Review'] = df['Review'].map(lambda x: x.lstrip('Not Verified | '))

df.head()

,Unnamed: 0,Review,Aircraft,Travel Type,Seat Type,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Value For Money,Recommendation
0,0,Organised boarding process. Really friendly cr...,A320,Business,Economy Class,January 2023,5,5,4,5,5,yes
1,1,Outward journey BA245 London to Buenos Aires C...,A320,Couple Leisure,Premium Economy,January 2023,3,1,1,4,1,no
2,2,Check in agent at LHR was very helpful and fri...,Boeing 777-300,Solo Leisure,Premium Economy,January 2023,4,4,1,4,1,no
3,3,y disappointing. I book BA so I can fly during...,Boeing 777-300,Solo Leisure,Economy Class,January 2023,1,2,1,4,3,no
4,4,Excellent service both on the ground and on bo...,A380,Solo Leisure,First Class,January 2023,4,5,4,5,4,yes

In [5]:
sentiment_pipeline = pipeline("sentiment-analysis",model="distilbert-base-uncased-finetuned-sst-2-english")

df["sentinment"]=df["Review"].apply(lambda x: sentiment_pipeline(x[:512]))

In [6]:
df.head()

,Unnamed: 0,Review,Aircraft,Travel Type,Seat Type,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Value For Money,Recommendation,sentinment
0,0,Organised boarding process. Really friendly cr...,A320,Business,Economy Class,January 2023,5,5,4,5,5,yes,"[{'label': 'POSITIVE', 'score': 0.999815762042..."
1,1,Outward journey BA245 London to Buenos Aires C...,A320,Couple Leisure,Premium Economy,January 2023,3,1,1,4,1,no,"[{'label': 'NEGATIVE', 'score': 0.998686015605..."
2,2,Check in agent at LHR was very helpful and fri...,Boeing 777-300,Solo Leisure,Premium Economy,January 2023,4,4,1,4,1,no,"[{'label': 'NEGATIVE', 'score': 0.999347984790..."
3,3,y disappointing. I book BA so I can fly during...,Boeing 777-300,Solo Leisure,Economy Class,January 2023,1,2,1,4,3,no,"[{'label': 'NEGATIVE', 'score': 0.999586164951..."
4,4,Excellent service both on the ground and on bo...,A380,Solo Leisure,First Class,January 2023,4,5,4,5,4,yes,"[{'label': 'POSITIVE', 'score': 0.999736011028..."

In [7]:

df.to_csv(r"C:\Users\Metin\Desktop\Data Science - Jupyter\britishairlines_internship\data\BA_reviews_sentiment1.csv")